# Generated by Django 2.2 on 2020-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_create_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall',
            old_name='slug',
            new_name='wall_link',
        ),
        migrations.AddField(
            model_name='wall',
            name='tags',
            field=models.TextField(blank=True, help_text='Please add meta tags by comma seperate', null=True),
        ),
    ]
