# Generated by Django 2.2 on 2020-06-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_circle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='circles',
        ),
        migrations.AddField(
            model_name='wall',
            name='circles',
            field=models.ManyToManyField(blank=True, to='Site.Circle'),
        ),
    ]
