# Generated by Django 2.2 on 2020-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20200623_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
